import type { FastifyPluginAsync } from 'fastify';
import usersRoutes from '../modules/users/routes.js';
import companiesRoutes from '../modules/companies/routes.js';
import dashboardRoutes from '../modules/dashboard/routes.js';
import notificationsRoutes from '../modules/notifications/routes.js';
import { chatAdminRoutes } from '../modules/chat/routes.js';
import { newsletterAdminRoutes } from '../modules/newsletter/routes.js';
import { contactAdminRoutes } from '../modules/contact/routes.js';
import { inquiriesAdminRoutes } from '../modules/inquiries/routes.js';
import { partnersAdminRoutes } from '../modules/partners/routes.js';
import { uploadsAdminRoutes } from '../modules/uploads/routes.js';
import { invitesAdminRoutes } from '../modules/invites/routes.js';
import { ordersAdminCrossRoutes, ordersAdminRoutes } from '../modules/orders/routes.js';
import exportsAdminRoutes from '../modules/exports/routes.js';
import pushAdminRoutes from '../modules/push/routes.js';
import { qrAdminRoutes } from '../modules/qr/routes.js';
import tasksAdminRoutes from '../modules/tasks/routes.js';
import { reviewsAdminRoutes } from '../modules/reviews/routes.js';
import subscriptionsAdminRoutes from '../modules/subscriptions/routes.js';
import invoicesAdminRoutes from '../modules/invoices/routes.js';
import cityStatusAdminRoutes from '../modules/city-status/routes.js';
import customersAdminRoutes from '../modules/customers/routes.js';
import priceAdjustmentsAdminRoutes from '../modules/price-adjustments/routes.js';
import { seoAdminRoutes } from '../modules/seo/routes.js';

const adminRoutes: FastifyPluginAsync = async (app) => {
  app.addHook('preHandler', app.requireAudience('admin'));

  await app.register(usersRoutes, { prefix: '/users' });
  await app.register(companiesRoutes, { prefix: '/companies' });
  await app.register(dashboardRoutes, { prefix: '/dashboard' });
  await app.register(notificationsRoutes, { prefix: '/notifications' });
  await app.register(newsletterAdminRoutes, { prefix: '/newsletter' });
  await app.register(contactAdminRoutes, { prefix: '/contact' });
  await app.register(inquiriesAdminRoutes, { prefix: '/inquiries' });
  await app.register(partnersAdminRoutes, { prefix: '/partners' });
  await app.register(uploadsAdminRoutes, { prefix: '/uploads' });
  await app.register(invitesAdminRoutes, { prefix: '/invites' });
  await app.register(chatAdminRoutes, { prefix: '/chat' });
  await app.register(ordersAdminCrossRoutes);
  await app.register(ordersAdminRoutes, { prefix: '/orders' });
  await app.register(pushAdminRoutes, { prefix: '/push' });
  await app.register(tasksAdminRoutes, { prefix: '/tasks' });
  await app.register(exportsAdminRoutes, { prefix: '/exports' });
  await app.register(qrAdminRoutes, { prefix: '/qr' });
  await app.register(reviewsAdminRoutes, { prefix: '/reviews' });
  await app.register(subscriptionsAdminRoutes, { prefix: '/subscriptions' });
  await app.register(invoicesAdminRoutes, { prefix: '/invoices' });
  await app.register(cityStatusAdminRoutes, { prefix: '/city-status' });
  await app.register(customersAdminRoutes, { prefix: '/customers' });
  await app.register(priceAdjustmentsAdminRoutes, { prefix: '/price-adjustments' });
  await app.register(seoAdminRoutes, { prefix: '/seo-pages' });
};

export default adminRoutes;
